### ISSUE TITLE
ACPI: sleep states S3 S4 S5

### ISSUE THREAD

**Issue by creatv21** [wowbroforce/acer-aspire-e5-573g-el-capitan#1]
can't get past this message"ACPI: sleep states S3 S4 S5" while booting, also tried with your latest SMBIOS;
if i drop all OEM SSDTs or drop "SSDT ACRPRDCT 23244"  i can boot to installer but SATA HDD isn't shown in disk utility

Laptop model: E5-573G-5147

EDIT: i used ur patched SSDTs & DSDT in ACPI/patched folder and finally my SATA HDD is visible in installer 
GREAT WORK 👍

**Comment by wowbroforce** [comment]
@creatv21 hi, can you tell me more in details, what did you do to make SATA HDD visible?

**Comment by creatv21** [comment]
i downloaded ur disassemble branch, copied the content of DSDT folder to my usb's EFI/clover/AHCI/patched folder. and i was using ur new-smbiosv2 config.plist.

**Comment by wowbroforce** [comment]
@creatv21 thanks, it's nice to hear this repo helped someone :)

**Comment by creatv21** [comment]
@wowbroforce will you add DSDT patches for audio and brightness fix?

**Comment by wowbroforce** [comment]
I would like to, but currently I'm stuck with invisible SATA HDD during installation. I will try again and if I succeed I will add all nessesary stuff.

**Comment by creatv21** [comment]
@wowbroforce i was trying to fix this problem with help of RehabMan in tonymacx86 forums. check this link, i've posted my updated clover folder there which helped me to get installation done.
http://www.tonymacx86.com/threads/hackintosh-acer-aspire-e5-573g-52g3.185462/page-9

**Comment by creatv21** [comment]
i got some kernel panics in my previous installation when i was trying to fix ACPI, then i downloaled your new master branch u fixed yesterday and reinstalled & installation went flawless! then i fixed brightness with inject intel and addPNLF.fixed audio with voodoo and LAN with realtek 8111 kexts. now only ACPI and brightness control with keys remains. :) @wowbroforce

**Comment by ayibfanani** [comment]
my sound is working with voodooHDA but my microphone not working, can you help me ? please

**Comment by wowbroforce** [comment]
Hi! 
Sorry, but I can't help you with your problem. You can go to http://tinymacx86.com and ask for help there.

**Comment by marcelodonnici** [comment]
Hello wowbroforce. Thanks very much for sharing this. You saved me! With the patched ssdt's I was able to resolve my issue (Installer not seeing internal HDD). Thank you.
I have a question for you. I'm not able to edit the graphics card (laggy screen, etc). It says graphic card 7mb. Were you able to resolve this? If so, can you please share? Thanks again very much!

**Comment by wowbroforce** [comment]
@marcelodonnici Get the latest Clover Configurator and check your config.plist on mac os x EFI partition. Go to Graphics section and check "ig-platform-id" (for my laptop's model it should be 0x16260006) and "Inject Intel" (should be checked).

**Comment by marcelodonnici** [comment]
Hey, thanks for the quick reply. Mine is 0x16260002 and Inject Intel checked. Did you mod your bios to set DVMT to 64mb or you didn't have to? Did you also experience graphic issues like mine? Thanks again!

**Comment by wowbroforce** [comment]
@marcelodonnici Yeap, I have set DVMT to something >= 64 mb. You can do it easy without modding your BIOS - check out [this article](http://wowbroforce.com/2016/07/26/how-to-unlock-advanced-tab-in-insydeh2o-bios/), hope it helps.

**Comment by marcelodonnici** [comment]
thanks a lot! Unfortunately, didn't work for me :( I tried a lot of times. Is it FN+Tab three times (holding both keys at the same time?) Unfortunately, didn't work. Thanks a lot!

**Comment by marcelodonnici** [comment]
Dude, I did it!!!! You're a freaking genius!! Thanks. You saved a lot of time!! Thank you.

**Comment by marcelodonnici** [comment]
Hi, sorry to bother again. Can you please tell me, besides setting DVMT to 64MB, if there's anything else you set up in your bios? Thanks again very much.

**Comment by wowbroforce** [comment]
Virtualization should be disabled.

**Comment by creatv21** [comment]
@marcelodonnici set DVMT to 96MB according to tonymacx86 forum. and it'll work with injectintel on

**Comment by marcelodonnici** [comment]
Thanks creatv21 and wowbroforce. When I set DVMT in bios to 96MB it didn't boot. Could you guys please share your config.plist? If you could also please tell what kexts you used to fix this?
Thanks very much in advance.

**Comment by wowbroforce** [comment]
@marcelodonnici Check out `legacy` branch for my final `config.plist` if you still need it.

**Comment by marcelodonnici** [comment]
Thanks wowbroforce! I really appreciate all your help. 
I'm personally stuck at "Graphic Card 7MB". Were you able to fix this?
My bios is configured as follows:
Intel Virtualization: Disabled
Vt-d: Disabled
SG: Disabled
Internal Graphic set as main graphic card (IGFX). The default was SG
DVMT: 128MB (it won't boot at 96MB)
Did you have to patch DSDT to get it to work?

Thanks again and I apologize for all the questions.

**Comment by wowbroforce** [comment]
@marcelodonnici Sorry, but I can't help you with this because we have laptops with different specs. You can visit http://www.tonymacx86.com/forums/el-capitan-laptop-support.181/ and ask for help there.

**Comment by marcelodonnici** [comment]
Will do. Thanks again wowbroforce.
